version: '3'

networks:
    catalog-net:

services:
    db:
        image: mariadb:latest
        container_name: catalog-mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=Keajm5dS95YR68
            - MARIADB_PASSWORD=Keajm5dS95YR68
            - MARIADB_USER=catalog
            - MARIADB_DATABASE=catalog_db
        volumes:
            - './database/db:/var/lib/mysql'
        networks:
            - catalog-net
    phpmyadmin:
        container_name: catalog-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 1024M
            MEMORY_LIMIT: 1024M
        restart: always
        ports:
            - 6997:80
        networks:
            - catalog-net
    webserver:
        image: nginx:latest
        container_name: catalog-nginx
        restart: unless-stopped
        ports:
            - "6999:80"
            - "6998:443"
        volumes:
            - ./:/var/www/html
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            - catalog-net

    app:
        build:
            context: .docker/php
            dockerfile: dockerfile
        container_name: catalog-php
        volumes:
            - ./:/var/www/html
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - catalog-net
