FROM php:8.1-fpm

USER root

# Setup working directory
WORKDIR /var/www/html
# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    nodejs \
    npm \
    unzip \
    sudo

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd
# Install Postgre PDO
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql
RUN npm install -g n
RUN n latest
RUN npm install -g npm@latest
# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
EXPOSE 9000
CMD ["php-fpm"]
